version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ops_evaluation
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 12

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ops_evaluation
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # tell the app where sample files live
      APP_IMPORT_PATH: /import/sample-project
      # optional toggle to enable/disable automatic import runner
      APP_IMPORT_ENABLED: "false"
    # mount sample-project from host into container so you can update files without rebuilding
    volumes:
      - ./sample-project:/import/sample-project:ro
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  frontend:
    build:
      context: .
      dockerfile: ops-candidate-evaluation-frontend/Dockerfile
      args:
        VITE_API_BASE_URL: "/api"
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db-data: